<?xml version="1.0" encoding="utf-8"?><Database Name="al" Class="MissionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=S1\S1;Initial Catalog=al;Persist Security Info=True;User ID=sa" SettingsObjectName="CheckMissions.Properties.Settings" SettingsPropertyName="alConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_schedule" Member="tbl_schedule">
    <Type Name="tbl_schedule">
      <Column Name="mid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="smid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="iid" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SDATE" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VIST" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="N" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="remark" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.p_institute" Member="p_institute">
    <Type Name="p_institute">
      <Column Name="iid" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="sname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="onDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="offDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="remark" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_check_mission_chronic_by_SDATE_VIST" Method="sp_check_mission_chronic_by_SDATE_VIST">
    <Parameter Name="d" Type="System.DateTime" DbType="Date" />
    <Parameter Name="VIST" Parameter="vIST" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="sp_check_mission_chronic_by_SDATE_VISTResult">
      <Column Name="total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="chronic" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_check_mission_person_by_sname_SDATE_VIST" Method="sp_check_mission_person_by_sname_SDATE_VIST">
    <Parameter Name="i" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="d" Type="System.DateTime" DbType="Date" />
    <Parameter Name="VIST" Parameter="vIST" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="sp_check_mission_person_by_sname_SDATE_VISTResult">
      <Column Name="r_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="uid" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="cname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="COMMENT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_check_mission_medication_by_sname_SDATE_VIST" Method="sp_check_mission_medication_by_sname_SDATE_VIST">
    <Parameter Name="i" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="d" Type="System.DateTime" DbType="Date" />
    <Parameter Name="VIST" Parameter="vIST" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="sp_check_mission_medication_by_sname_SDATE_VISTResult">
      <Column Name="r_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="uid" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="cname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="r06" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TIME_QTY1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TIMES_DAY" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="METHOD" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="COMMENT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>